version: "3"
services:
  ac-server:
    image: harbor.lishang4.com/fju/ac-server:${TAG:-latest}
    container_name: ac-server
    volumes:
      - /etc/localtime:/etc/localtime
    restart: always
    deploy:
      resources:
        limits:
          memory: 1024M
    ports:
      - "8765:8765"
    environment:
      - TW_PORT=8765
      - WD_HOST=172.104.123.152
      - WS_PORT=8765
    networks:
      - emotibot
networks:
  emotibot:
    external:
      name: emotibot
